// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNmPGJFtCKs0uR1641ZtMzjvePBCwl3H0',
    appId: '1:352417946428:web:e5a265153233a5ec9f5c39',
    messagingSenderId: '352417946428',
    projectId: 'gallery-190c9',
    authDomain: 'gallery-190c9.firebaseapp.com',
    storageBucket: 'gallery-190c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuMG62P39pCKPpQXLrr-9cBLhvCQcx2Bo',
    appId: '1:352417946428:android:37c526457e22a6a79f5c39',
    messagingSenderId: '352417946428',
    projectId: 'gallery-190c9',
    storageBucket: 'gallery-190c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTZZS4bUJ9vIJIoCZAcAmJBvB0ev6dPuc',
    appId: '1:352417946428:ios:9feb0780029e79f99f5c39',
    messagingSenderId: '352417946428',
    projectId: 'gallery-190c9',
    storageBucket: 'gallery-190c9.firebasestorage.app',
    iosBundleId: 'com.example.gallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTZZS4bUJ9vIJIoCZAcAmJBvB0ev6dPuc',
    appId: '1:352417946428:ios:9feb0780029e79f99f5c39',
    messagingSenderId: '352417946428',
    projectId: 'gallery-190c9',
    storageBucket: 'gallery-190c9.firebasestorage.app',
    iosBundleId: 'com.example.gallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNmPGJFtCKs0uR1641ZtMzjvePBCwl3H0',
    appId: '1:352417946428:web:52ecd405e85c85ef9f5c39',
    messagingSenderId: '352417946428',
    projectId: 'gallery-190c9',
    authDomain: 'gallery-190c9.firebaseapp.com',
    storageBucket: 'gallery-190c9.firebasestorage.app',
  );

}